/// Build info provided by the CI build process.
/// WARNING: This file is automatically generated by the CI process
/// and should not be changed unless changing the scripts as well.
///
public enum CIBuildInfo {
    /// Dictionary containing the info generated by the CI process.
    public static let info: KeyValuePairs<String, String> = [:]
}
