import BitwardenKit
import Foundation
import Testing

/// Tests for `SDKVersionInfo`.
struct SDKVersionInfoTests {
    /// `version` is not "Unknown" since the build script should have generated it.
    @Test
    func versionIsNotUnknown() {
        #expect(
            SDKVersionInfo.version != "Unknown",
            "SDK version should be generated by build script, not 'Unknown'",
        )
    }

    /// `version` is not empty.
    @Test
    func versionIsNotEmpty() {
        #expect(!SDKVersionInfo.version.isEmpty)
    }

    /// `version` matches the expected semantic version format from project-common.yml.
    /// Expected format: "MAJOR.MINOR.PATCH-BUILD_NUMBER-COMMIT_HASH"
    /// Example: "2.0.0-3659-948b207"
    @Test
    func versionMatchesSemanticVersionFormat() {
        let version = SDKVersionInfo.version

        // Regex pattern for semantic version with build number and commit hash
        // Format: X.Y.Z-BUILD-HASH where:
        // - X.Y.Z is the semantic version (e.g., 2.0.0)
        // - BUILD is the build number (e.g., 3659)
        // - HASH is the short git commit hash (e.g., 948b207)
        let pattern = #"^\d+\.\d+\.\d+-\d+-[a-f0-9]+$"#

        let regex = try? NSRegularExpression(pattern: pattern, options: [])
        let range = NSRange(version.startIndex..., in: version)
        let matches = regex?.firstMatch(in: version, options: [], range: range)

        #expect(
            matches != nil,
            "SDK version '\(version)' should match format 'X.Y.Z-BUILD-HASH' (e.g., '2.0.0-3659-948b207')",
        )
    }
}
