ignore:
  - "**/*Tests*/**"
  - "**/TestHelpers/**"
  - "**/Fixtures/**"
  - "GlobalTestHelpers/**"
  - "GlobalTestHelpers-bwa/**"
  - "GlobalTestHelpers-bwth/**"
  - "**/Mocks/**"
  - "**/*Mock*.swift"
