/// Build info provided by the CI build process.
/// WARNING: This file is automatically generated by the CI process
/// and should not be changed unless changing the scripts as well.
///
enum CIBuildInfo {
    /// Dictionary containing the info generated by the CI process.
    static let info: [String: String] = [:]
}
