import Foundation

/// A model representing a one time password code generated by the sdk.
///
public struct TOTPCodeModel: Equatable {
    /// The code string.
    ///
    var code: String

    /// The date used to generate the code.
    ///
    var codeGenerationDate: Date

    /// The code formatted for display
    ///
    var displayCode: String {
        code.enumerated().map { index, character in
            guard (index + 1) % 3 == 0 else { return "\(character)" }
            return "\(character) "
        }.joined()
    }

    /// The period of the code.
    ///
    var period: UInt32
}
