# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
# https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
# https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do |options|
    desc "Push a new build to TestFlight"
    lane :upload_build do |options|
    upload_to_testflight(
        skip_submission: false,
        changelog: options[:changelog],
        skip_waiting_for_build_processing: false,
        api_key_path: options[:api_key_path],
        ipa: options[:ipa_path],
        localized_build_info: {
            "default": {
                whats_new: options[:changelog],
            }
        }
    )
    end

    desc "Get latest published version"
    lane :get_latest_version do
        app_store_build_number(
            api_key_path: options[:api_key_path]
        )
        latest_version = lane_context[SharedValues::LATEST_VERSION]

        sh("echo STORE_VERSION=#{latest_version} >> $GITHUB_ENV")
    end
end
