import Foundation

// MARK: - TOTPCodeModel

/// A model representing a one time password code generated by the sdk.
///
public struct TOTPCodeModel: Equatable, Sendable {
    // MARK: Properties

    /// The code string.
    ///
    public var code: String

    /// The date used to generate the code.
    ///
    public var codeGenerationDate: Date

    /// The code formatted for display.
    ///
    public var displayCode: String {
        code.enumerated().map { index, character in
            guard (index + 1) % 3 == 0 else { return "\(character)" }
            return "\(character) "
        }
        .joined()
        .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// The period of the code.
    ///
    public var period: UInt32

    // MARK: Initialization

    /// Initializes a `TOTPCodeModel`.
    ///
    /// - Parameters:
    ///   - code: The OTP code string.
    ///   - codeGenerationDate: The date the code was generated.
    ///   - period: The validity period of the code, in seconds.
    ///
    public init(code: String, codeGenerationDate: Date, period: UInt32) {
        self.code = code
        self.codeGenerationDate = codeGenerationDate
        self.period = period
    }
}
