name: Build for Simulator

on:
  workflow_dispatch:
    inputs:
      build-version:
        description: "Unused"

jobs:
  build:
    name: Build
    runs-on: macos-14

    steps:
      - name: Check out repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          filter: tree:0
