name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      artifact-run-id:
        description: 'GitHub Action Run ID containing artifacts'
        required: true
        type: string
      release-ticket-id:
        description: 'Release Ticket ID - e.g. RELEASE-1762'
        required: true
        type: string

permissions: {}

jobs:
  trigger-actions:
    name: Trigger release-ios in bitwarden/deploy
    runs-on: ubuntu-24.04
    permissions:
      deployments: write
    steps:
      - name: Trigger release-ios workflow
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          task: release-ios
          repo: ios
          branch: ${{ github.ref_name }}
          data: |
            {
              "artifact-run-id": "${{ inputs.artifact-run-id }}",
              "release-ticket-id": "${{ inputs.release-ticket-id }}"
            }
