name: Update public suffix list
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

permissions:
  contents: read

jobs:
  psl-update:
    name: Update PSL
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Download latest PSL list
        run: | 
          curl https://publicsuffix.org/list/public_suffix_list.dat \
          -o BitwardenShared/Core/Platform/Utilities/Resources/public_suffix_list.dat

      - name: Create pull-request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update public suffix list"
          title: "Update public suffix list"
          body: "Update the public suffix list"
          branch: update-public-suffix-list
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
