name: Test Password Manager

on:
  push:
    branches:
      - main
      - release/**/*
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - Authenticator/**
      - AuthenticatorShared/**
  workflow_dispatch:
    inputs:
      xcode-version:
        description: "Xcode version override - e.g. '15.2'"
        type: string
      simulator-name:
        description: "Simulator name override - e.g. 'iPhone 16 Pro'"
        type: string
      simulator-version:
        description: "Simulator iOS version override - e.g. '18.0.1'"
        type: string
      compiler-flags:
        description: "Compiler Flags - e.g. 'DEBUG_MENU FEATURE2'"
        type: string
  workflow_call:
    inputs:
      xcode-version:
        description: "Xcode version override - e.g. '15.2'"
        type: string
      simulator-name:
        description: "Simulator name override - e.g. 'iPhone 16 Pro'"
        type: string
      simulator-version:
        description: "Simulator iOS version override - e.g. '18.0.1'"
        type: string
      compiler-flags:
        description: "Compiler Flags - e.g. 'DEBUG_MENU FEATURE2'"
        type: string

env:
  MINT_LINK_PATH: .mint/bin # used by mint in bootstrap.sh
  MINT_PATH: .mint/lib # used by mint in bootstrap.sh
  _COVERAGE_PATH: build/coverage.xml
  _BUILD_RESULT_BUNDLE_PATH: build/bwpm-build.xcresult
  _TESTS_RESULT_BUNDLE_PATH: build/bwpm-tests.xcresult
  _SIMULATOR_NAME: ${{ inputs.simulator-name }}
  _SIMULATOR_VERSION: ${{ inputs.simulator-version }}
  _XCODE_VERSION: ${{ inputs.xcode-version }}
  _COMPILER_FLAGS: ${{ inputs.compiler-flags }}
  _GITHUB_ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}

  # xcode optimization flags
  COMPILER_INDEX_STORE_ENABLE: "NO"
  COMPILATION_CACHE_ENABLE_CACHING: "YES"
  COMPILATION_CACHE_ENABLE_PLUGIN: "YES"
  SWIFT_ENABLE_COMPILE_CACHE: "YES"
  CLANG_ENABLE_COMPILE_CACHE: "YES"
  SWIFT_ENABLE_EXPLICIT_MODULES: "YES"
  SWIFT_USE_INTEGRATED_DRIVER: "YES"
  CLANG_ENABLE_MODULES: "YES"

jobs:
  test:
    name: Test
    runs-on: macos-26-xlarge
    timeout-minutes: 50
    permissions:
      contents: read

    steps:
      - name: Log inputs to job summary
        uses: bitwarden/ios/.github/actions/log-inputs@main
        with:
          inputs: "${{ toJson(inputs) }}"

      - name: Check out repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Optimize macOS Runner
        uses: ./.github/actions/macos-runner-tuneup

      - name: Read Xcode version and simulator configuration from file if not provided
        run: |
          if [ -z "$_XCODE_VERSION" ]; then
            echo "_XCODE_VERSION=$(cat .xcode-version | tr -d '\n')" >> "$GITHUB_ENV"
          fi
          if [ -z "$_SIMULATOR_NAME" ]; then
            echo "_SIMULATOR_NAME=$(cat .test-simulator-device-name | tr -d '\n')" >> "$GITHUB_ENV"
          fi
          if [ -z "$_SIMULATOR_VERSION" ]; then
            echo "_SIMULATOR_VERSION=$(cat .test-simulator-ios-version | tr -d '\n')" >> "$GITHUB_ENV"
          fi

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env._XCODE_VERSION }}

      - name: Configure Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          bundler-cache: true

      - name: Restore Mint packages
        id: restore-mint
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Restore SPM packages
        id: restore-spm
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Restore DerivedData
        id: restore-deriveddata
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build/DerivedData
          key: ${{ runner.os }}-deriveddata-testbwpm-${{ env._XCODE_VERSION }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-deriveddata-testbwpm-${{ env._XCODE_VERSION }}-

      # src: https://stackoverflow.com/questions/53753511/is-it-possible-to-copy-an-xcode-derived-data-cache
      - name: Set IgnoreFileSystemDeviceInodeChanges flag
        run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Update local config
        run: |
          ./Scripts/update_test_local_config.sh "${_COMPILER_FLAGS}"

      - name: Install Homebrew Dependencies and run bootstrap.sh
        run: |
          brew update
          brew bundle
          ./Scripts/bootstrap.sh

      - name: Boot Simulator
        id: boot-simulator
        uses: ./.github/actions/boot-simulator
        with:
          simulator-name: ${{ env._SIMULATOR_NAME }}
          simulator-version: ${{ env._SIMULATOR_VERSION }}

      - name: Build
        env:
          _SIMULATOR_ID: ${{ steps.boot-simulator.outputs.simulator-id }}
        run: |
            python Scripts/pyeetd/main.py & PYEETD_PID=$!
            xcrun xcodebuild build-for-testing \
              -workspace Bitwarden.xcworkspace \
              -scheme Bitwarden \
              -configuration Debug \
              -destination "platform=iOS Simulator,id=$_SIMULATOR_ID" \
              -derivedDataPath build/DerivedData \
              -resultBundlePath "$_BUILD_RESULT_BUNDLE_PATH" \
              -parallelizeTargets \
              -skipPackagePluginValidation \
              -skipMacroValidation \
              -showBuildTimingSummary \
              -quiet
            kill "$PYEETD_PID"

      - name: Save Mint packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.restore-mint.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

      - name: Save SPM packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.restore-spm.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Save DerivedData
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.restore-deriveddata.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build/DerivedData
          key: ${{ runner.os }}-deriveddata-testbwpm-${{ env._XCODE_VERSION }}-${{ github.sha }}

      - name: Test
        id: test
        env:
          _SIMULATOR_ID: ${{ steps.boot-simulator.outputs.simulator-id }}
        run: |
            python Scripts/pyeetd/main.py & PYEETD_PID=$!
            xcrun xcodebuild test-without-building \
              -workspace Bitwarden.xcworkspace \
              -scheme Bitwarden \
              -configuration Debug \
              -destination "platform=iOS Simulator,id=$_SIMULATOR_ID" \
              -resultBundlePath "$_TESTS_RESULT_BUNDLE_PATH" \
              -derivedDataPath build/DerivedData \
              -test-timeouts-enabled yes \
              -maximum-test-execution-time-allowance 3 \
              -showBuildTimingSummary \
              -quiet
            kill "$PYEETD_PID"

      - name: Print Logs Summary
        if: always() && steps.test.outcome != 'skipped'
        run: |
          xcresultparser -f -o cli "$_TESTS_RESULT_BUNDLE_PATH"
          xcresultparser -f -o txt "$_TESTS_RESULT_BUNDLE_PATH" >> "$GITHUB_STEP_SUMMARY"

      - name: Convert coverage to Cobertura
        run: |
          set -o pipefail && \
            xcresultparser --output-format cobertura \
            "$_TESTS_RESULT_BUNDLE_PATH" > "$_COVERAGE_PATH"

      - name: Upload test reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-reports
          compression-level: 9
          path: |
            ${{ env._COVERAGE_PATH }}
            ${{ env._TESTS_RESULT_BUNDLE_PATH }}
            ${{ env._BUILD_RESULT_BUNDLE_PATH }}

  report:
    name: Process Test Reports
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write
    if: success()

    steps:
      - name: Check out repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout: .github/codecov.yml
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Download test artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: test-reports

      - name: Upload to codecov.io
        id: upload-to-codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        continue-on-error: true
        with:
          files: coverage.xml
          fail_ci_if_error: true
          version: v11.2.3 # Do not bump until this is fixed: https://github.com/getsentry/prevent-cli/issues/101

      - name: Comment PR if tests failed
        if: steps.upload-to-codecov.outcome == 'failure'
        env:
            PR_NUMBER: ${{ github.event.number }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            RUN_ACTOR: ${{ github.triggering_actor }}
        run: |
          echo "> [!WARNING]" >> "$GITHUB_STEP_SUMMARY"
          echo "> Uploading code coverage report failed. Please check the \"Upload to codecov.io\" step of \"Process Test Reports\" job for more details." >> "$GITHUB_STEP_SUMMARY"

          if [ ! -z "$PR_NUMBER" ]; then
            message=$'> [!WARNING]\n> @'$RUN_ACTOR' Uploading code coverage report failed. Please check the "Upload to codecov.io" step of [Process Test Reports job]('$_GITHUB_ACTION_RUN_URL') for more details.'
            gh pr comment --repo "$GITHUB_REPOSITORY" "$PR_NUMBER" --body "$message"
          fi
